import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    // Per-component subpath entry points
    "components/accordion": "src/components/accordion.tsx",
    "components/alert": "src/components/alert.tsx",
    "components/alert-dialog": "src/components/alert-dialog.tsx",
    "components/animated-counter": "src/components/animated-counter.tsx",
    "components/approval-actions": "src/components/approval-actions.tsx",
    "components/ascii-shader": "src/components/ascii-shader.tsx",
    "components/aspect-ratio": "src/components/aspect-ratio.tsx",
    "components/audit-log": "src/components/audit-log.tsx",
    "components/avatar": "src/components/avatar.tsx",
    "components/badge": "src/components/badge.tsx",
    "components/bg-shader": "src/components/bg-shader.tsx",
    "components/blocky-shader": "src/components/blocky-shader.tsx",
    "components/breadcrumb": "src/components/breadcrumb.tsx",
    "components/button": "src/components/button.tsx",
    "components/button-group": "src/components/button-group.tsx",
    "components/calendar": "src/components/calendar.tsx",
    "components/callout": "src/components/callout.tsx",
    "components/card": "src/components/card.tsx",
    "components/carousel": "src/components/carousel.tsx",
    "components/case-card": "src/components/case-card.tsx",
    "components/chart": "src/components/chart.tsx",
    "components/checkbox": "src/components/checkbox.tsx",
    "components/code-block": "src/components/code-block.tsx",
    "components/collapsible": "src/components/collapsible.tsx",
    "components/combobox": "src/components/combobox.tsx",
    "components/command": "src/components/command.tsx",
    "components/comment-thread": "src/components/comment-thread.tsx",
    "components/compliance-score": "src/components/compliance-score.tsx",
    "components/context-menu": "src/components/context-menu.tsx",
    "components/copy-button": "src/components/copy-button.tsx",
    "components/data-table": "src/components/data-table.tsx",
    "components/date-picker": "src/components/date-picker.tsx",
    "components/deadline-countdown": "src/components/deadline-countdown.tsx",
    "components/description-list": "src/components/description-list.tsx",
    "components/dialog": "src/components/dialog.tsx",
    "components/direction": "src/components/direction.tsx",
    "components/drawer": "src/components/drawer.tsx",
    "components/dropdown-menu": "src/components/dropdown-menu.tsx",
    "components/empty": "src/components/empty.tsx",
    "components/entity-header": "src/components/entity-header.tsx",
    "components/fade-in": "src/components/fade-in.tsx",
    "components/field": "src/components/field.tsx",
    "components/file-upload": "src/components/file-upload.tsx",
    "components/filter-bar": "src/components/filter-bar.tsx",
    "components/form": "src/components/form.tsx",
    "components/grid": "src/components/grid.tsx",
    "components/hover-card": "src/components/hover-card.tsx",
    "components/inline-edit": "src/components/inline-edit.tsx",
    "components/input": "src/components/input.tsx",
    "components/input-group": "src/components/input-group.tsx",
    "components/input-otp": "src/components/input-otp.tsx",
    "components/item": "src/components/item.tsx",
    "components/kbd": "src/components/kbd.tsx",
    "components/label": "src/components/label.tsx",
    "components/loading-overlay": "src/components/loading-overlay.tsx",
    "components/logo-vasp": "src/components/logo-vasp.tsx",
    "components/marquee": "src/components/marquee.tsx",
    "components/menubar": "src/components/menubar.tsx",
    "components/native-select": "src/components/native-select.tsx",
    "components/navigation-menu": "src/components/navigation-menu.tsx",
    "components/number-input": "src/components/number-input.tsx",
    "components/pagination": "src/components/pagination.tsx",
    "components/policy-banner": "src/components/policy-banner.tsx",
    "components/popover": "src/components/popover.tsx",
    "components/progress": "src/components/progress.tsx",
    "components/radio-group": "src/components/radio-group.tsx",
    "components/resizable": "src/components/resizable.tsx",
    "components/risk-gauge": "src/components/risk-gauge.tsx",
    "components/scroll-area": "src/components/scroll-area.tsx",
    "components/search-input": "src/components/search-input.tsx",
    "components/segmented-control": "src/components/segmented-control.tsx",
    "components/select": "src/components/select.tsx",
    "components/separator": "src/components/separator.tsx",
    "components/shadow-root-host": "src/components/shadow-root-host.tsx",
    "components/sheet": "src/components/sheet.tsx",
    "components/sidebar": "src/components/sidebar.tsx",
    "components/skeleton": "src/components/skeleton.tsx",
    "components/slider": "src/components/slider.tsx",
    "components/sonner": "src/components/sonner.tsx",
    "components/spinner": "src/components/spinner.tsx",
    "components/split-pane": "src/components/split-pane.tsx",
    "components/stat": "src/components/stat.tsx",
    "components/status-indicator": "src/components/status-indicator.tsx",
    "components/step-progress": "src/components/step-progress.tsx",
    "components/streaming-cards": "src/components/streaming-cards.tsx",
    "components/striped-bar": "src/components/striped-bar.tsx",
    "components/subtle-shader": "src/components/subtle-shader.tsx",
    "components/switch": "src/components/switch.tsx",
    "components/table": "src/components/table.tsx",
    "components/tabs": "src/components/tabs.tsx",
    "components/tag": "src/components/tag.tsx",
    "components/textarea": "src/components/textarea.tsx",
    "components/theme-script": "src/components/theme-script.tsx",
    "components/timeline": "src/components/timeline.tsx",
    "components/toggle": "src/components/toggle.tsx",
    "components/toggle-group": "src/components/toggle-group.tsx",
    "components/tooltip": "src/components/tooltip.tsx",
    "components/typewriter": "src/components/typewriter.tsx",
    "components/typography": "src/components/typography.tsx",
    "components/visually-hidden": "src/components/visually-hidden.tsx",
    "components/waffle-chart": "src/components/waffle-chart.tsx",
    // Per-hook entry points
    "hooks/use-animation-timer": "src/hooks/use-animation-timer.ts",
    "hooks/use-carousel": "src/hooks/use-carousel.ts",
    "hooks/use-clipboard": "src/hooks/use-clipboard.ts",
    "hooks/use-cycle-index": "src/hooks/use-cycle-index.ts",
    "hooks/use-debounce": "src/hooks/use-debounce.ts",
    "hooks/use-disclosure": "src/hooks/use-disclosure.ts",
    "hooks/use-intersection-observer": "src/hooks/use-intersection-observer.ts",
    "hooks/use-local-storage": "src/hooks/use-local-storage.ts",
    "hooks/use-media-query": "src/hooks/use-media-query.ts",
    "hooks/use-mobile": "src/hooks/use-mobile.ts",
    // Icon entry points
    "icons/pixel": "src/icons/pixel.tsx",
    // Lib entry points
    "lib/utils": "src/lib/utils.ts",
    "lib/animation": "src/lib/animation.ts",
    // Shell entry points
    "shells/app-shell": "src/shells/app-shell.tsx",
    // Per-animation entry points for code-splitting (next/dynamic)
    "animations/animation-ai-analysis": "src/animations/animation-ai-analysis.tsx",
    "animations/animation-audit-trail": "src/animations/animation-audit-trail.tsx",
    "animations/animation-compliance-reports": "src/animations/animation-compliance-reports.tsx",
    "animations/animation-custom-rules": "src/animations/animation-custom-rules.tsx",
    "animations/animation-jira-ticket": "src/animations/animation-jira-ticket.tsx",
    "animations/animation-jurisdiction-detection": "src/animations/animation-jurisdiction-detection.tsx",
    "animations/animation-multi-protocol": "src/animations/animation-multi-protocol.tsx",
    "animations/animation-pricing-preview": "src/animations/animation-pricing-preview.tsx",
    "animations/animation-realtime-updates": "src/animations/animation-realtime-updates.tsx",
    "animations/animation-rest-api": "src/animations/animation-rest-api.tsx",
    "animations/animation-risk-scoring": "src/animations/animation-risk-scoring.tsx",
    "animations/animation-sandbox": "src/animations/animation-sandbox.tsx",
    "animations/animation-scheduled-reports": "src/animations/animation-scheduled-reports.tsx",
    "animations/animation-secure-messaging": "src/animations/animation-secure-messaging.tsx",
    "animations/animation-slack-notification": "src/animations/animation-slack-notification.tsx",
    "animations/animation-sop-mapping": "src/animations/animation-sop-mapping.tsx",
    "animations/animation-team-routing": "src/animations/animation-team-routing.tsx",
    "animations/animation-teams-notification": "src/animations/animation-teams-notification.tsx",
    "animations/animation-vasp-identification": "src/animations/animation-vasp-identification.tsx",
    "animations/animation-webhooks": "src/animations/animation-webhooks.tsx",
    // Block entry points
    "blocks/pricing-table": "src/blocks/pricing-table.tsx",
    "blocks/stat-card": "src/blocks/stat-card.tsx",
    "blocks/feature-section": "src/blocks/feature-section.tsx",
    "blocks/hero-section": "src/blocks/hero-section.tsx",
    "blocks/login-form": "src/blocks/login-form.tsx",
    "blocks/register-form": "src/blocks/register-form.tsx",
    "blocks/rich-radio-list": "src/blocks/rich-radio-list.tsx",
    "blocks/sequence-builder": "src/blocks/sequence-builder.tsx",
    "blocks/forgot-password-form": "src/blocks/forgot-password-form.tsx",
    "blocks/select-org-form": "src/blocks/select-org-form.tsx",
    "blocks/magic-link-message": "src/blocks/magic-link-message.tsx",
    "blocks/setting-row": "src/blocks/setting-row.tsx",
    "blocks/settings-card-grid": "src/blocks/settings-card-grid.tsx",
    // Chart entry point
    charts: "src/charts/index.ts",
    // Workflow entry point
    workflow: "src/workflow/index.ts",
    // Chatbot entry point
    chatbot: "src/chatbot/index.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  tsconfig: "tsconfig.package.json",
  external: [
    "react",
    "react-dom",
    "react/jsx-runtime",
    "tailwindcss",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "lucide-react",
    "@base-ui/react",
    "cmdk",
    "vaul",
    "sonner",
    "embla-carousel-react",
    "recharts",
    "react-resizable-panels",
    "@tanstack/react-form",
    "@tanstack/react-table",
    "@tanstack/react-virtual",
    "date-fns",
    "react-day-picker",
    "input-otp",
    "motion",
    "motion/react",
    "next",
    "next/link",
    "next/font/google",
    "next/image",
    "next/dynamic",
    "@xyflow/react",
    "@xyflow/react/dist/style.css",
  ],
  treeshake: true,
  onSuccess: `node -e "var fs=require('fs'),path=require('path');function walk(d){fs.readdirSync(d,{withFileTypes:true}).forEach(function(f){var fp=path.join(d,f.name);if(f.isDirectory()){walk(fp);return}if(!f.name.endsWith('.js'))return;var c=fs.readFileSync(fp,'utf8');if(c.indexOf('use client')>=0)return;if(c.indexOf('from \\'react\\'')>=0||c.indexOf('from \\'react/jsx-runtime\\'')>=0){fs.writeFileSync(fp,'\\\"use client\\\";\\n'+c)}})}walk('dist')"`,
})
