import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    // Per-component entry points for code-splitting (next/dynamic)
    "animations/animation-ai-analysis": "src/animations/animation-ai-analysis.tsx",
    "animations/animation-audit-trail": "src/animations/animation-audit-trail.tsx",
    "animations/animation-compliance-reports": "src/animations/animation-compliance-reports.tsx",
    "animations/animation-custom-rules": "src/animations/animation-custom-rules.tsx",
    "animations/animation-jira-ticket": "src/animations/animation-jira-ticket.tsx",
    "animations/animation-jurisdiction-detection": "src/animations/animation-jurisdiction-detection.tsx",
    "animations/animation-multi-protocol": "src/animations/animation-multi-protocol.tsx",
    "animations/animation-pricing-preview": "src/animations/animation-pricing-preview.tsx",
    "animations/animation-realtime-updates": "src/animations/animation-realtime-updates.tsx",
    "animations/animation-rest-api": "src/animations/animation-rest-api.tsx",
    "animations/animation-risk-scoring": "src/animations/animation-risk-scoring.tsx",
    "animations/animation-sandbox": "src/animations/animation-sandbox.tsx",
    "animations/animation-scheduled-reports": "src/animations/animation-scheduled-reports.tsx",
    "animations/animation-secure-messaging": "src/animations/animation-secure-messaging.tsx",
    "animations/animation-slack-notification": "src/animations/animation-slack-notification.tsx",
    "animations/animation-sop-mapping": "src/animations/animation-sop-mapping.tsx",
    "animations/animation-team-routing": "src/animations/animation-team-routing.tsx",
    "animations/animation-teams-notification": "src/animations/animation-teams-notification.tsx",
    "animations/animation-vasp-identification": "src/animations/animation-vasp-identification.tsx",
    "animations/animation-webhooks": "src/animations/animation-webhooks.tsx",
    // Block entry points
    "blocks/pricing-table": "src/blocks/pricing-table.tsx",
    "blocks/stat-card": "src/blocks/stat-card.tsx",
    "blocks/feature-section": "src/blocks/feature-section.tsx",
    "blocks/hero-section": "src/blocks/hero-section.tsx",
    "blocks/auth-form": "src/blocks/auth-form.tsx",
    // Chart entry point
    charts: "src/charts/index.ts",
    // Workflow entry point
    workflow: "src/workflow/index.ts",
    // Chatbot entry point
    chatbot: "src/chatbot/index.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  tsconfig: "tsconfig.package.json",
  external: [
    "react",
    "react-dom",
    "react/jsx-runtime",
    "tailwindcss",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "lucide-react",
    "@base-ui/react",
    "cmdk",
    "vaul",
    "sonner",
    "embla-carousel-react",
    "recharts",
    "react-resizable-panels",
    "@tanstack/react-form",
    "@tanstack/react-table",
    "@tanstack/react-virtual",
    "zod",
    "date-fns",
    "react-day-picker",
    "input-otp",
    "motion",
    "motion/react",
    "next",
    "next/link",
    "next/font/google",
    "next/image",
    "next/dynamic",
    "@xyflow/react",
    "@xyflow/react/dist/style.css",
  ],
  treeshake: true,
  onSuccess: `node -e "var fs=require('fs'),path=require('path');function walk(d){fs.readdirSync(d,{withFileTypes:true}).forEach(function(f){var fp=path.join(d,f.name);if(f.isDirectory()){walk(fp);return}if(!f.name.endsWith('.js'))return;var c=fs.readFileSync(fp,'utf8');if(c.indexOf('use client')<0){fs.writeFileSync(fp,'\\\"use client\\\";\\n'+c)}})}walk('dist')"`,
})
