import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    // Per-component subpath entry points
    "components/accordion": "src/components/accordion.tsx",
    "components/alert": "src/components/alert.tsx",
    "components/alert-dialog": "src/components/alert-dialog.tsx",
    "components/animated-counter": "src/components/animated-counter.tsx",
    "components/approval-actions": "src/components/approval-actions.tsx",
    "components/ascii-shader": "src/components/ascii-shader.tsx",
    "components/aspect-ratio": "src/components/aspect-ratio.tsx",
    "components/audit-log": "src/components/audit-log.tsx",
    "components/avatar": "src/components/avatar.tsx",
    "components/badge": "src/components/badge.tsx",
    "components/bg-shader": "src/components/bg-shader.tsx",
    "components/blocky-shader": "src/components/blocky-shader.tsx",
    "components/breadcrumb": "src/components/breadcrumb.tsx",
    "components/button": "src/components/button.tsx",
    "components/button-group": "src/components/button-group.tsx",
    "components/calendar": "src/components/calendar.tsx",
    "components/card": "src/components/card.tsx",
    "components/carousel": "src/components/carousel.tsx",
    "components/chart": "src/components/chart.tsx",
    "components/checkbox": "src/components/checkbox.tsx",
    "components/code-block": "src/components/code-block.tsx",
    "components/collapsible": "src/components/collapsible.tsx",
    "components/combobox": "src/components/combobox.tsx",
    "components/command": "src/components/command.tsx",
    "components/context-menu": "src/components/context-menu.tsx",
    "components/copy-button": "src/components/copy-button.tsx",
    "components/data-table": "src/components/data-table.tsx",
    "components/date-picker": "src/components/date-picker.tsx",
    "components/deadline-countdown": "src/components/deadline-countdown.tsx",
    "components/dialog": "src/components/dialog.tsx",
    "components/drawer": "src/components/drawer.tsx",
    "components/dropdown-menu": "src/components/dropdown-menu.tsx",
    "components/empty": "src/components/empty.tsx",
    "components/header": "src/components/header.tsx",
    "components/fade-in": "src/components/fade-in.tsx",
    "components/field": "src/components/field.tsx",
    "components/file-upload": "src/components/file-upload.tsx",
    "components/filter-bar": "src/components/filter-bar.tsx",
    "components/form": "src/components/form.tsx",
    "components/grid": "src/components/grid.tsx",
    "components/hover-card": "src/components/hover-card.tsx",
    "components/inline-edit": "src/components/inline-edit.tsx",
    "components/input": "src/components/input.tsx",
    "components/input-group": "src/components/input-group.tsx",
    "components/input-otp": "src/components/input-otp.tsx",
    "components/item": "src/components/item.tsx",
    "components/kbd": "src/components/kbd.tsx",
    "components/label": "src/components/label.tsx",
    "components/loading-overlay": "src/components/loading-overlay.tsx",
    "components/logo-vasp": "src/components/logo-vasp.tsx",
    "components/marquee": "src/components/marquee.tsx",
    "components/menubar": "src/components/menubar.tsx",
    "components/native-select": "src/components/native-select.tsx",
    "components/navigation-menu": "src/components/navigation-menu.tsx",
    "components/number-input": "src/components/number-input.tsx",
    "components/pagination": "src/components/pagination.tsx",
    "components/policy-banner": "src/components/policy-banner.tsx",
    "components/popover": "src/components/popover.tsx",
    "components/progress": "src/components/progress.tsx",
    "components/radio-group": "src/components/radio-group.tsx",
    "components/resizable": "src/components/resizable.tsx",
    "components/risk-gauge": "src/components/risk-gauge.tsx",
    "components/scroll-area": "src/components/scroll-area.tsx",
    "components/search-input": "src/components/search-input.tsx",
    "components/segmented-control": "src/components/segmented-control.tsx",
    "components/select": "src/components/select.tsx",
    "components/separator": "src/components/separator.tsx",
    "components/shadow-root-host": "src/components/shadow-root-host.tsx",
    "components/sheet": "src/components/sheet.tsx",
    "components/sidebar": "src/components/sidebar.tsx",
    "components/skeleton": "src/components/skeleton.tsx",
    "components/slider": "src/components/slider.tsx",
    "components/sonner": "src/components/sonner.tsx",
    "components/spinner": "src/components/spinner.tsx",
    "components/split-pane": "src/components/split-pane.tsx",
    "components/stat": "src/components/stat.tsx",
    "components/status-indicator": "src/components/status-indicator.tsx",
    "components/step": "src/components/step.tsx",
    "components/streaming-cards": "src/components/streaming-cards.tsx",
    "components/striped-bar": "src/components/striped-bar.tsx",
    "components/subtle-shader": "src/components/subtle-shader.tsx",
    "components/switch": "src/components/switch.tsx",
    "components/table": "src/components/table.tsx",
    "components/tabs": "src/components/tabs.tsx",
    "components/textarea": "src/components/textarea.tsx",
    "components/theme-script": "src/components/theme-script.tsx",
    "components/timeline": "src/components/timeline.tsx",
    "components/toggle": "src/components/toggle.tsx",
    "components/toggle-group": "src/components/toggle-group.tsx",
    "components/tooltip": "src/components/tooltip.tsx",
    "components/typewriter": "src/components/typewriter.tsx",
    "components/typography": "src/components/typography.tsx",
    "components/virtualized-grid": "src/components/virtualized-grid.tsx",
    "components/visually-hidden": "src/components/visually-hidden.tsx",
    "components/waffle-chart": "src/components/waffle-chart.tsx",
    // Per-hook entry points
    "hooks/use-animation-timer": "src/hooks/use-animation-timer.ts",
    "hooks/use-carousel": "src/hooks/use-carousel.ts",
    "hooks/use-clipboard": "src/hooks/use-clipboard.ts",
    "hooks/use-cycle-index": "src/hooks/use-cycle-index.ts",
    "hooks/use-debounce": "src/hooks/use-debounce.ts",
    "hooks/use-disclosure": "src/hooks/use-disclosure.ts",
    "hooks/use-intersection-observer": "src/hooks/use-intersection-observer.ts",
    "hooks/use-local-storage": "src/hooks/use-local-storage.ts",
    "hooks/use-media-query": "src/hooks/use-media-query.ts",
    "hooks/use-mobile": "src/hooks/use-mobile.ts",
    "hooks/use-css-vars": "src/hooks/use-css-vars.ts",
    // Lib entry points
    "lib/utils": "src/lib/utils.ts",
    "lib/animation": "src/lib/animation.ts",
    "lib/icon-map": "src/lib/icon-map.tsx",
    // Shell entry points
    "shells/app-shell": "src/shells/app-shell.tsx",
    "shells/app-shell-2": "src/shells/app-shell-2.tsx",
    "shells/settings-layout": "src/shells/settings-layout.tsx",
    // Layout entry points (page-level compositions)
    "layouts/dashboard-page": "src/layouts/dashboard-page.tsx",
    "layouts/transaction-detail-page": "src/layouts/transaction-detail-page.tsx",
    // Per-animation entry points for code-splitting (next/dynamic)
    "animations/animation-ai-analysis": "src/animations/animation-ai-analysis.tsx",
    "animations/animation-audit-trail": "src/animations/animation-audit-trail.tsx",
    "animations/animation-compliance-reports": "src/animations/animation-compliance-reports.tsx",
    "animations/animation-custom-rules": "src/animations/animation-custom-rules.tsx",
    "animations/animation-jira-ticket": "src/animations/animation-jira-ticket.tsx",
    "animations/animation-jurisdiction-detection": "src/animations/animation-jurisdiction-detection.tsx",
    "animations/animation-multi-protocol": "src/animations/animation-multi-protocol.tsx",
    "animations/animation-pricing-preview": "src/animations/animation-pricing-preview.tsx",
    "animations/animation-realtime-updates": "src/animations/animation-realtime-updates.tsx",
    "animations/animation-rest-api": "src/animations/animation-rest-api.tsx",
    "animations/animation-risk-scoring": "src/animations/animation-risk-scoring.tsx",
    "animations/animation-sandbox": "src/animations/animation-sandbox.tsx",
    "animations/animation-scheduled-reports": "src/animations/animation-scheduled-reports.tsx",
    "animations/animation-secure-messaging": "src/animations/animation-secure-messaging.tsx",
    "animations/animation-slack-notification": "src/animations/animation-slack-notification.tsx",
    "animations/animation-sop-mapping": "src/animations/animation-sop-mapping.tsx",
    "animations/animation-team-routing": "src/animations/animation-team-routing.tsx",
    "animations/animation-teams-notification": "src/animations/animation-teams-notification.tsx",
    "animations/animation-vasp-identification": "src/animations/animation-vasp-identification.tsx",
    "animations/animation-webhooks": "src/animations/animation-webhooks.tsx",
    // Block entry points
    "blocks/api-key-manager": "src/blocks/api-key-manager.tsx",
    "blocks/changelog": "src/blocks/changelog.tsx",
    "blocks/command-palette": "src/blocks/command-palette.tsx",
    "blocks/invoice": "src/blocks/invoice.tsx",
    "blocks/kanban": "src/blocks/kanban.tsx",
    "blocks/multi-step-form": "src/blocks/multi-step-form.tsx",
    "blocks/notification-center": "src/blocks/notification-center.tsx",
    "blocks/page-header": "src/blocks/page-header.tsx",
    "blocks/pricing-table": "src/blocks/pricing-table.tsx",
    "blocks/team-table": "src/blocks/team-table.tsx",
    "blocks/usage-meter": "src/blocks/usage-meter.tsx",
    "blocks/product-tour": "src/blocks/product-tour.tsx",
    "blocks/stat-card": "src/blocks/stat-card.tsx",
    "blocks/feature-section": "src/blocks/feature-section.tsx",
    "blocks/hero-section": "src/blocks/hero-section.tsx",
    "blocks/login-form": "src/blocks/login-form.tsx",
    "blocks/register-form": "src/blocks/register-form.tsx",
    "blocks/rich-radio-list": "src/blocks/rich-radio-list.tsx",
    "blocks/sequence-builder": "src/blocks/sequence-builder.tsx",
    "blocks/forgot-password-form": "src/blocks/forgot-password-form.tsx",
    "blocks/select-org-form": "src/blocks/select-org-form.tsx",
    "blocks/magic-link-message": "src/blocks/magic-link-message.tsx",
    "blocks/setting-row": "src/blocks/setting-row.tsx",
    "blocks/settings-card-grid": "src/blocks/settings-card-grid.tsx",
    "blocks/workspace-switcher": "src/blocks/workspace-switcher.tsx",
    "blocks/chat": "src/blocks/chat.tsx",
    "blocks/prompt-input-actions": "src/blocks/prompt-input-actions.tsx",
    "blocks/prompt-input-suggestions": "src/blocks/prompt-input-suggestions.tsx",
    // Chart entry points — per-chart subpaths for tree-shaking
    charts: "src/charts/index.ts",
    "charts/area-chart": "src/charts/area-chart.tsx",
    "charts/bar-chart": "src/charts/bar-chart.tsx",
    "charts/composed-chart": "src/charts/composed-chart.tsx",
    "charts/funnel-chart": "src/charts/funnel-chart.tsx",
    "charts/heatmap-chart": "src/charts/heatmap-chart.tsx",
    "charts/line-chart": "src/charts/line-chart.tsx",
    "charts/pie-chart": "src/charts/pie-chart.tsx",
    "charts/radial-chart": "src/charts/radial-chart.tsx",
    "charts/scatter-chart": "src/charts/scatter-chart.tsx",
    // Workflow entry points — per-module subpaths for tree-shaking
    workflow: "src/workflow/index.ts",
    "workflow/canvas": "src/workflow/canvas.tsx",
    "workflow/entity-graph": "src/workflow/entity-graph.tsx",
    "workflow/workflow-block-palette": "src/workflow/workflow-block-palette.tsx",
    "workflow/workflow-inspector": "src/workflow/workflow-inspector.tsx",
    "workflow/workflow-slack-message": "src/workflow/workflow-slack-message.tsx",
    "workflow/workflow-connection": "src/workflow/workflow-connection.tsx",
    "workflow/workflow-context": "src/workflow/workflow-context.tsx",
    "workflow/workflow-controls": "src/workflow/workflow-controls.tsx",
    "workflow/workflow-edge": "src/workflow/workflow-edge.tsx",
    "workflow/workflow-gate": "src/workflow/workflow-gate.tsx",
    "workflow/workflow-group": "src/workflow/workflow-group.tsx",
    "workflow/workflow-handle": "src/workflow/workflow-handle.tsx",
    "workflow/workflow-label": "src/workflow/workflow-label.tsx",
    "workflow/workflow-minimap": "src/workflow/workflow-minimap.tsx",
    "workflow/workflow-node": "src/workflow/workflow-node.tsx",
    "workflow/workflow-node-card": "src/workflow/workflow-node-card.tsx",
    "workflow/workflow-panel": "src/workflow/workflow-panel.tsx",
    "workflow/workflow-toolbar": "src/workflow/workflow-toolbar.tsx",
    // Compliance entry points — per-component subpaths for tree-shaking
    compliance: "src/compliance/index.ts",
    "compliance/address-display": "src/compliance/address-display.tsx",
    "compliance/audit-note": "src/compliance/audit-note.tsx",
    "compliance/case-card": "src/compliance/case-card.tsx",
    "compliance/chain-icons": "src/compliance/chain-icons.tsx",
    "compliance/compliance-score": "src/compliance/compliance-score.tsx",
    "compliance/status-helpers": "src/compliance/status-helpers.tsx",
    "compliance/counterparty-card": "src/compliance/counterparty-card.tsx",
    "compliance/jurisdiction-card": "src/compliance/jurisdiction-card.tsx",
    "compliance/network-badge": "src/compliance/network-badge.tsx",
    "compliance/report-export": "src/compliance/report-export.tsx",
    "compliance/review-form": "src/compliance/review-form.tsx",
    "compliance/risk-score-inline": "src/compliance/risk-score-inline.tsx",
    "compliance/transaction-card": "src/compliance/transaction-card.tsx",
    "compliance/transaction-detail": "src/compliance/transaction-detail.tsx",
    "compliance/transaction-filters": "src/compliance/transaction-filters.tsx",
    "compliance/transaction-row": "src/compliance/transaction-row.tsx",
    // Chatbot entry point
    chatbot: "src/chatbot/index.ts",
    "chatbot/agent-progress": "src/chatbot/agent-progress.tsx",
    "chatbot/markdown": "src/chatbot/markdown.tsx",
    // Workflow diagram — inline SVG workflow renderer + animated beam
    "workflow-diagram": "src/workflow-diagram/index.ts",
    "workflow-diagram/workflow-diagram": "src/workflow-diagram/workflow-diagram.tsx",
    "workflow-diagram/animated-beam": "src/workflow-diagram/animated-beam.tsx",
    // Card stack — scattered rotated-card hero composition
    "card-stack": "src/card-stack/index.ts",
    // Bento — feature-page bento visuals
    bento: "src/bento/index.ts",
    "bento/card-grid": "src/bento/card-grid.tsx",
    "bento/checklist": "src/bento/checklist.tsx",
    "bento/decision-record": "src/bento/decision-record.tsx",
    "bento/feed": "src/bento/feed.tsx",
    "bento/mapping-matrix": "src/bento/mapping-matrix.tsx",
    "bento/profile": "src/bento/profile.tsx",
    "bento/retention-table": "src/bento/retention-table.tsx",
    "bento/rule-checklist": "src/bento/rule-checklist.tsx",
    "bento/score": "src/bento/score.tsx",
    "bento/search-panel": "src/bento/search-panel.tsx",
    "bento/skill-match": "src/bento/skill-match.tsx",
    "bento/transition-card": "src/bento/transition-card.tsx",
    "bento/types": "src/bento/types.ts",
    // Showcase — feature-page in-panel showcase animations
    showcase: "src/showcase/index.ts",
    "showcase/action": "src/showcase/action.tsx",
    "showcase/detail": "src/showcase/detail.tsx",
    "showcase/sources": "src/showcase/sources.tsx",
    "showcase/steps": "src/showcase/steps.tsx",
    "showcase/version-history": "src/showcase/version-history.tsx",
    "showcase/types": "src/showcase/types.ts",
  },
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  tsconfig: "tsconfig.package.json",
  external: [
    "react",
    "react-dom",
    "react/jsx-runtime",
    "tailwindcss",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "lucide-react",
    "@base-ui/react",
    "cmdk",
    "vaul",
    "sonner",
    "embla-carousel-react",
    "recharts",
    "react-resizable-panels",
    "@tanstack/react-form",
    "@tanstack/react-table",
    "@tanstack/react-virtual",
    "date-fns",
    "react-day-picker",
    "input-otp",
    "motion",
    "motion/react",
    "next",
    "next/link",
    "next/font/google",
    "next/image",
    "next/dynamic",
    "@xyflow/react",
    "@xyflow/react/dist/style.css",
    "pixelarticons/react",
    "streamdown",
  ],
  treeshake: true,
  onSuccess: `node -e "var fs=require('fs'),path=require('path');function walk(d){fs.readdirSync(d,{withFileTypes:true}).forEach(function(f){var fp=path.join(d,f.name);if(f.isDirectory()){walk(fp);return}if(!f.name.endsWith('.js'))return;var c=fs.readFileSync(fp,'utf8');if(c.indexOf('use client')>=0)return;if(c.indexOf('from \\'react\\'')>=0||c.indexOf('from \\'react/jsx-runtime\\'')>=0){fs.writeFileSync(fp,'\\\"use client\\\";\\n'+c)}})}walk('dist')"`,
})
